"""Curated catalog of widely-used BLS series IDs.

This is what ``bls_list_popular_series`` and ``bls_search_series`` index.
Each entry has the same shape so consumers can treat them uniformly. Series
IDs were verified against BLS series ID guides at the time of authoring.
"""

from __future__ import annotations

from typing import Final

# Each entry: {id, title, units, frequency, seasonal_adjustment, survey, notes}
POPULAR_SERIES: Final[dict[str, list[dict[str, str]]]] = {
    "Prices — CPI headline & core": [
        {
            "id": "CUUR0000SA0",
            "title": "CPI-U: All items (NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "Headline CPI, used for COLA-style indexation and 12-month inflation reporting.",
        },
        {
            "id": "CUSR0000SA0",
            "title": "CPI-U: All items (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Seasonally-adjusted headline CPI — use for clean MoM and MoM-annualized inflation.",
        },
        {
            "id": "CUUR0000SA0L1E",
            "title": "CPI-U: All items less food and energy (Core CPI, NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "Core CPI, NSA variant.",
        },
        {
            "id": "CUSR0000SA0L1E",
            "title": "CPI-U: All items less food and energy (Core CPI, SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Seasonally-adjusted Core CPI — Fed's preferred CPI gauge of underlying inflation.",
        },
        {
            "id": "CWUR0000SA0",
            "title": "CPI-W: All items (NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "Basis for Social Security COLA.",
        },
        {
            "id": "SUUR0000SA0",
            "title": "C-CPI-U: All items (chained CPI)",
            "units": "Index Dec 1999=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "Chained CPI; tax-bracket indexation since TCJA.",
        },
    ],
    "Prices — CPI components": [
        {
            "id": "CUSR0000SAF1",
            "title": "CPI-U: Food (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Food component of headline CPI.",
        },
        {
            "id": "CUSR0000SA0E",
            "title": "CPI-U: Energy (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Energy component of headline CPI.",
        },
        {
            "id": "CUSR0000SAH1",
            "title": "CPI-U: Shelter (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Shelter — the largest core CPI weight.",
        },
        {
            "id": "CUSR0000SEHA",
            "title": "CPI-U: Rent of primary residence (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Tenant rent — leads shelter inflation by ~6-12 months.",
        },
        {
            "id": "CUSR0000SEHC",
            "title": "CPI-U: Owners' equivalent rent of residences (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "OER — dominant shelter weight in core CPI.",
        },
        {
            "id": "CUSR0000SASLE",
            "title": "CPI-U: Services less energy services (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "'Supercore' services inflation — Fed-watched.",
        },
        {
            "id": "CUSR0000SAM",
            "title": "CPI-U: Medical care (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Medical care services + commodities.",
        },
        {
            "id": "CUSR0000SAT",
            "title": "CPI-U: Transportation (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Transportation services + commodities.",
        },
        {
            "id": "CUSR0000SETA02",
            "title": "CPI-U: Used cars and trucks (SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Volatile post-COVID inflation driver.",
        },
        {
            "id": "CUSR0000SETB01",
            "title": "CPI-U: Gasoline (all types, SA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPI",
            "notes": "Largest energy component swing factor.",
        },
    ],
    "Prices — Regional CPI": [
        {
            "id": "CUUR0100SA0",
            "title": "CPI-U: Northeast region — All items (NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "",
        },
        {
            "id": "CUUR0200SA0",
            "title": "CPI-U: Midwest region — All items (NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "",
        },
        {
            "id": "CUUR0300SA0",
            "title": "CPI-U: South region — All items (NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "",
        },
        {
            "id": "CUUR0400SA0",
            "title": "CPI-U: West region — All items (NSA)",
            "units": "Index 1982-84=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "CPI",
            "notes": "",
        },
    ],
    "Prices — PPI": [
        {
            "id": "WPSFD4",
            "title": "PPI: Final demand (NSA)",
            "units": "Index Nov 2009=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "PPI",
            "notes": "Headline PPI final demand.",
        },
        {
            "id": "WPSFD49207",
            "title": "PPI: Final demand less foods and energy (Core PPI, NSA)",
            "units": "Index Nov 2009=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "PPI",
            "notes": "Core PPI ex food & energy.",
        },
        {
            "id": "WPSFD49116",
            "title": "PPI: Final demand less foods, energy, and trade services",
            "units": "Index Nov 2009=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "PPI",
            "notes": "PPI 'super-core' — closest analog to core PCE goods-pipeline pressure.",
        },
        {
            "id": "WPUID61",
            "title": "PPI: Intermediate demand by commodity — Stage 4",
            "units": "Index",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "PPI",
            "notes": "Pipeline pressure indicator.",
        },
        {
            "id": "WPSFD41312",
            "title": "PPI: Final demand services (NSA)",
            "units": "Index Nov 2009=100",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "PPI",
            "notes": "Services PPI.",
        },
    ],
    "Labor — Household (CPS)": [
        {
            "id": "LNS14000000",
            "title": "Unemployment Rate (U-3)",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "Headline unemployment rate, 16 years and over.",
        },
        {
            "id": "LNS13327709",
            "title": "U-6: Total unemployed plus marginally attached plus PT for economic reasons",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "Broadest BLS measure of labor underutilization.",
        },
        {
            "id": "LNS13023621",
            "title": "U-1: Long-term unemployed (15+ weeks) as % of labor force",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "Tightest underutilization measure.",
        },
        {
            "id": "LNS13023705",
            "title": "U-2: Job losers and persons who completed temp jobs as % of labor force",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "",
        },
        {
            "id": "LNS13327708",
            "title": "U-4: U-3 plus discouraged workers",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "",
        },
        {
            "id": "LNS13327707",
            "title": "U-5: U-4 plus other marginally attached",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "",
        },
        {
            "id": "LNS11300000",
            "title": "Labor Force Participation Rate",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "Civilian labor force as a share of the civilian noninstitutional population.",
        },
        {
            "id": "LNS12300000",
            "title": "Employment-Population Ratio",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "Employed as a share of civilian noninstitutional population.",
        },
        {
            "id": "LNS11000000",
            "title": "Civilian Labor Force level",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "",
        },
        {
            "id": "LNS12000000",
            "title": "Employed level (CPS)",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "Household-survey employment level.",
        },
        {
            "id": "LNS13000000",
            "title": "Unemployed level",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "",
        },
        {
            "id": "LNS15000000",
            "title": "Not in labor force",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CPS",
            "notes": "",
        },
    ],
    "Labor — Establishment (CES)": [
        {
            "id": "CES0000000001",
            "title": "Total nonfarm employment, All employees",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "Headline nonfarm payrolls (establishment survey).",
        },
        {
            "id": "CES0500000001",
            "title": "Total private, All employees",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "Private payrolls.",
        },
        {
            "id": "CES0500000003",
            "title": "Total private: Average hourly earnings (AHE), All employees",
            "units": "Dollars per hour",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "Wage growth proxy.",
        },
        {
            "id": "CES0500000002",
            "title": "Total private: Average weekly hours (AWH), All employees",
            "units": "Hours",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "Wage-x-hours signal.",
        },
        {
            "id": "CES0500000011",
            "title": "Total private: Average weekly earnings, All employees",
            "units": "Dollars",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
        {
            "id": "CES0600000001",
            "title": "Goods-producing employment",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
        {
            "id": "CES0800000001",
            "title": "Service-providing employment",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
        {
            "id": "CES3000000001",
            "title": "Manufacturing employment",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
        {
            "id": "CES4200000001",
            "title": "Retail trade employment",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
        {
            "id": "CES7000000001",
            "title": "Leisure and hospitality employment",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
        {
            "id": "CES9000000001",
            "title": "Government employment",
            "units": "Thousands of persons",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "CES",
            "notes": "",
        },
    ],
    "Labor — JOLTS": [
        {
            "id": "JTS000000000000000JOL",
            "title": "Job openings, total nonfarm (level)",
            "units": "Thousands",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "JOLTS",
            "notes": "Headline job openings.",
        },
        {
            "id": "JTS000000000000000JOR",
            "title": "Job openings rate, total nonfarm",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "JOLTS",
            "notes": "Openings / (employment + openings).",
        },
        {
            "id": "JTS000000000000000HIL",
            "title": "Hires, total nonfarm (level)",
            "units": "Thousands",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "JOLTS",
            "notes": "",
        },
        {
            "id": "JTS000000000000000QUL",
            "title": "Quits, total nonfarm (level)",
            "units": "Thousands",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "JOLTS",
            "notes": "",
        },
        {
            "id": "JTS000000000000000QUR",
            "title": "Quits rate, total nonfarm",
            "units": "Percent",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "JOLTS",
            "notes": "Wage-pressure leading indicator.",
        },
        {
            "id": "JTS000000000000000LDL",
            "title": "Layoffs and discharges, total nonfarm (level)",
            "units": "Thousands",
            "frequency": "monthly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "JOLTS",
            "notes": "",
        },
    ],
    "Labor — ECI (Employment Cost Index)": [
        {
            "id": "CIU1010000000000A",
            "title": "ECI: Civilian workers, total compensation (12-month % change)",
            "units": "Percent change",
            "frequency": "quarterly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "ECI",
            "notes": "Comprehensive labor-cost gauge (wages + benefits).",
        },
        {
            "id": "CIS1010000000000I",
            "title": "ECI: Civilian workers, total compensation (index, SA)",
            "units": "Index Dec 2005=100",
            "frequency": "quarterly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "ECI",
            "notes": "",
        },
        {
            "id": "CIS2010000000000I",
            "title": "ECI: Private-industry workers, total compensation (index, SA)",
            "units": "Index Dec 2005=100",
            "frequency": "quarterly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "ECI",
            "notes": "",
        },
    ],
    "Productivity": [
        {
            "id": "PRS85006092",
            "title": "Nonfarm business sector: Labor productivity (output per hour), %ch QoQ at AR",
            "units": "Percent change at annual rate",
            "frequency": "quarterly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "PRODUCTIVITY",
            "notes": "Headline productivity.",
        },
        {
            "id": "PRS85006112",
            "title": "Nonfarm business sector: Unit labor costs, %ch QoQ at AR",
            "units": "Percent change at annual rate",
            "frequency": "quarterly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "PRODUCTIVITY",
            "notes": "Wages-per-unit-output cost pressure.",
        },
        {
            "id": "PRS30006092",
            "title": "Manufacturing sector: Labor productivity, %ch QoQ at AR",
            "units": "Percent change at annual rate",
            "frequency": "quarterly",
            "seasonal_adjustment": "seasonally adjusted",
            "survey": "PRODUCTIVITY",
            "notes": "",
        },
    ],
    "International prices": [
        {
            "id": "EIUIR",
            "title": "Import price index: All imports (NSA)",
            "units": "Index",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "IMPORT_EXPORT",
            "notes": "All-imports index — passes through to goods CPI.",
        },
        {
            "id": "EIUIR000",
            "title": "Import price index: All imports",
            "units": "Index",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "IMPORT_EXPORT",
            "notes": "",
        },
        {
            "id": "EIUIQ",
            "title": "Export price index: All exports (NSA)",
            "units": "Index",
            "frequency": "monthly",
            "seasonal_adjustment": "not seasonally adjusted",
            "survey": "IMPORT_EXPORT",
            "notes": "",
        },
    ],
}
